name: "Test Workflow"
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', 'pypy-3.7' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install libudev-dev
      - run: sudo apt-get install librrd-dev libpython3-dev
      - run: sudo apt-get install gcc --only-upgrade      
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with: 
          repository: smarthomeNG/smarthome
          ref: develop
          path: smarthomeng
      - uses: actions/checkout@v2
        with: 
          repository: smarthomeNG/plugins
          ref: develop
          path: smarthomeng/plugins
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python3 -m pip install --upgrade pip #==19.3.1    
      #- run: pip install tox-travis virtualenv>=20.0.8 --upgrade
      - run: pip install sphinx sphinx_rtd_theme recommonmark
      - run: python3 smarthomeng/tools/build_requirements.py
      - run: sh smarthomeng/tests/run.sh
      - run: python ./python/hello_world.py
